name: 'Contribution Inspector'
author: 'ranemihir/Flowdify'
description: 'A GitHub Action to monitor submitted issues & PRs.'

inputs:
  token: 
    description: 'GitHub Access Token'
    required: true

  issue--greeting-message:
    description: 'Message to show when an issue is created successfully'
    required: false
    default: 'Thanks for your contribution! :)'

  pull-request--greeting-message:
    description: 'Message to show when a pull request is created successfully'
    required: false
    default: 'Thanks for your contribution! :)'
    
  pull-request--size-small:
    description: 'Size of the pull request measured by the lines of code changed.'
    required: false
    default: 50
  pull-request--size-medium:
    description: 'Size of the pull request measured by the lines of code changed.'
    required: false
    default: 200
  pull-request--size-large:
    description: 'Size of the pull request measured by the lines of code changed.'
    required: false
    default: 400

  pull-request--one-commit-per-pr-for-small-pull-requests:
    description: 'If set to true, "One commit per PR" strategy will be impemented for small pull requests.'
    required: false
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
